branches:
  only:
    - master

language: objective-c
osx_image: xcode9.2

cache:
  - bundler

rvm:
  - 2.3

script: travis_retry .travis/run.sh

env:
  matrix:
    - LANE=lint
    - LANE=test
    - LANE=kscrash
    - LANE=swiftpm
    # - LANE=pod

jobs:
  include:
      env: LANE=deploy
      script: .travis/stage-carthage.sh
      after_success:
        - npm install -g @zeus-ci/cli
        - zeus upload -t "application/zip+carthage" KSCrash/Sentry.framework.zip

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/b0f1479e-c596-11e7-88ed-0a580a280308/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
