language: objective-c
osx_image: xcode7.3
rvm:
    - 2.2.3
before_install:
    - gem install fastlane
script: 
    - scan -s SentrySwift-iOS
    - scan -s SentrySwift-OSX
    - scan -s SentrySwift-tvOS
