name: unit-tests
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        pushCodecov: [true]
        destination:
          - platform=macOS,variant=Mac Catalyst
          - platform=iOS Simulator,OS=latest,name=iPhone 11 Pro
          - platform=tvOS Simulator,OS=14.0,name=Apple TV 4K
          # Can't run tests on watchOS because XCTest is not available
        
        # SentrySystemEventsBreadcrumbsTest don't run on macOS
        # so the coverage report shows a reduced coverage.
        include:
          - destination: platform=macOS
            pushCodecov: false

    steps:
      - name: ${{matrix.destination}}
      - uses: actions/checkout@v2
      - run: ./scripts/ci-select-xcode.sh

      - name: Running tests
        run: >-
          xcodebuild 
          -workspace Sentry.xcworkspace 
          -scheme Sentry 
          -configuration Debug 
          GCC_GENERATE_TEST_COVERAGE_FILES=YES 
          -destination "${{matrix.destination}}" 
          test | xcpretty -t && exit ${PIPESTATUS[0]}

      # We can upload all coverage reports, because codecov merges them.
      # See https://docs.codecov.io/docs/merging-reports
      - name: Push code coverage to codecov
        uses: codecov/codecov-action@v1
        if: ${{matrix.pushCodecov}}
        with:
          token: ${{secrets.CODECOV_TOKEN}}
