apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2
  retries: 3

defaults:
  timeout: 20m

xcuitest:
  app: ./DerivedData/Build/Products/Debug-iphoneos/iOS-Swift.app
  testApp: ./DerivedData/Build/Products/Debug-iphoneos/PerformanceBenchmarks-Runner.app

suites:
  - name: "High-end device"
    passThreshold: 2
    smartRetry:
      failedOnly: true
    devices:
      - name: "iPad Pro 12.9 2021"
        platformVersion: "15"

  - name: "Mid-range device"
    passThreshold: 2
    smartRetry:
      failedOnly: true
    devices:
      - name: "iPhone 8"
        platformVersion: "14"

  - name: "Low-end device"
    passThreshold: 2
    smartRetry:
      failedOnly: true
    devices:
      - name: "iPhone 6S"
        platformVersion: "15"
