apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 2

defaults:
  timeout: 20m

xcuitest:
  app: ./DerivedData/Build/Products/Test-iphoneos/iOS-Swift.app
  testApp: ./DerivedData/Build/Products/Test-iphoneos/iOS-SwiftUITests-Runner.app

suites:

  - name: "iOS-17"
    devices:
      - name: "iPhone.*"
        platformVersion: "17"

  - name: "iOS-16"
    devices:
      - name: "iPhone.*"
        platformVersion: "16"
   
  - name: "iOS-15"
    devices:
      - name: "iPhone.*"
        platformVersion: "15"

  - name: "iPhone-Pro"
    devices:
      - name: "iPhone 13 Pro.*"
        platformVersion: "15"
        
  - name: "iOS-14"
    devices:
      - name: "iPhone.*"
        platformVersion: "14"

  - name: "iOS-13"
    devices:
      - name: "iPhone.*"
        platformVersion: "13"

  - name: "iOS-12"
    devices:
      - name: "iPhone.*"
        platformVersion: "12"
      
artifacts:
  download:
    when: always
    match:
      - "*.junit.xml"
    directory: ./artifacts/
