apiVersion: v1alpha
kind: xcuitest
sauce:
  region: us-west-1
  concurrency: 4

defaults:
  timeout: 60m

xcuitest:
  app: ./DerivedData/Build/Products/Test-iphoneos/iOS-Swift.app
  testApp: ./DerivedData/Build/Products/Test-iphoneos/iOS-SwiftUITests-Runner.app

suites:
  # CI speed and reliability are essential for developer productivity. Running UI tests on SauceLabs
  # takes time, and when running multiple CI jobs in parallel for various PRs, SauceLabs becomes the
  # bottleneck. Ideally, we would run our UI tests on a wide range of devices with different OS
  # versions, but that's expensive and doesn't increase the likelihood of catching SDK bugs
  # significantly. Instead, we choose a minimum set of devices. Furthermore, our unit tests surface most
  # SDK bugs.
 
  # We need to run the tests on an iPhone Pro because it has 120Hz refresh rate.
  - name: "iOS-17"
    devices:
      - name: "iPhone .* Pro.*"
        platformVersion: "17"
   
  - name: "iOS-16"
    devices:
      - name: "iPhone.*"
        platformVersion: "16"

  - name: "iOS-12"
    devices:
      - name: "iPhone.*"
        platformVersion: "12"
